"Scn_Configuration As screen.'tabletAutoLayout_Sidebar_ver1.0'":
    LoadingSpinnerColor: =RGBA(98, 100, 167, 1)

    ScreenContainer2 As groupContainer.horizontalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        SidebarContainer2 As groupContainer.verticalAutoLayoutContainer:
            FillPortions: =3
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =2

        RightSideContainer2 As groupContainer.verticalAutoLayoutContainer:
            FillPortions: =7
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =3

            HeaderContainer2 As groupContainer.horizontalAutoLayoutContainer:
                FillPortions: =0
                Height: =75
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                ZIndex: =4

            MainSectionContainer2 As groupContainer.verticalAutoLayoutContainer:
                LayoutDirection: =LayoutDirection.Vertical
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                ZIndex: =5

