"Scn_Configuration As screen.'tabletAutoLayout_Sidebar_ver1.0'":
    Fill: =RGBA(240, 242, 245, 1)
    LoadingSpinnerColor: =RGBA(98, 100, 167, 1)

    ScreenContainer2 As groupContainer.horizontalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        SidebarContainer2 As groupContainer.verticalAutoLayoutContainer:
            LayoutDirection: =LayoutDirection.Vertical
            LayoutGap: =15
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingLeft: =5
            PaddingTop: =10
            ZIndex: =2

            Image1_2 As image:
                AlignInContainer: =AlignInContainer.Center
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledFill: =RGBA(0, 0, 0, 0)
                HoverBorderColor: =RGBA(0, 0, 0, 0)
                HoverFill: =RGBA(0, 0, 0, 0)
                Image: =undraw_online_test_gba7
                PressedBorderColor: =RGBA(0, 0, 0, 0)
                PressedFill: =RGBA(0, 0, 0, 0)
                RadiusBottomLeft: =3
                RadiusBottomRight: =3
                RadiusTopLeft: =3
                RadiusTopRight: =3
                X: =141
                Y: =18
                ZIndex: =1

            Button1_40 As button:
                AlignInContainer: =AlignInContainer.Center
                BorderColor: =
                BorderThickness: =0
                DisabledBorderColor: =RGBA(166, 166, 166, 1)
                DisabledColor: =RGBA(166, 166, 166, 1)
                DisabledFill: =RGBA(244, 244, 244, 1)
                Fill: =RGBA(238, 140, 29, 1)
                FocusedBorderThickness: =0
                Font: =Font.'Segoe UI'
                FontWeight: =FontWeight.Semibold
                HoverBorderColor: =RGBA(238, 140, 29, 1)
                HoverColor: =RGBA(255, 255, 255, 1)
                HoverFill: |-
                    =ColorFade(ColorValue("#EE8C1D"), -20%)
                OnSelect: =Back();
                PressedColor: =RGBA(255, 255, 255, 1)
                PressedFill: |-
                    =ColorFade(ColorValue("#EE8C1D"), -20%)
                RadiusBottomLeft: =5
                RadiusBottomRight: =5
                RadiusTopLeft: =5
                RadiusTopRight: =5
                Size: =12
                Text: ="Back"
                Width: =118
                X: =60
                Y: =48
                ZIndex: =2

            Gallery4 As gallery.BrowseLayout_Vertical_OneTextVariant_pcfCore:
                AlignInContainer: =AlignInContainer.Center
                BorderColor: =RGBA(243, 242, 241, 1)
                DelayItemLoading: =true
                FocusedBorderColor: =RGBA(98, 100, 167, 1)
                FocusedBorderThickness: =2
                Items: =SettingNavigationItems
                Layout: =Layout.Vertical
                LayoutMinHeight: =287
                LayoutMinWidth: =50
                LoadingSpinner: =LoadingSpinner.Data
                OnSelect: |-
                    =UpdateContext({SettingToDisplay : ThisItem.label});
                TemplateSize: =50
                Width: =Parent.Width
                ZIndex: =4

                Rectangle7 As rectangle:
                    BorderColor: =RGBA(243, 242, 241, 1)
                    DisabledFill: =RGBA(0,0,0,0)
                    Fill: =RGBA(255, 255, 255, 1)
                    FocusedBorderColor: =RGBA(98, 100, 167, 1)
                    Height: =Parent.TemplateHeight
                    HoverFill: =RGBA(0,0,0,0)
                    OnSelect: =Select(Parent)
                    PressedFill: =RGBA(0,0,0,0)
                    TabIndex: =0
                    Width: =Parent.TemplateWidth
                    ZIndex: =1

                Title6 As Label:
                    DisplayMode: =DisplayMode.Edit
                    FontSize: =10.5
                    FontWeight: =FontWeight.Normal
                    Height: =24
                    OnSelect: =Select(Parent)
                    PCFTeamsTheme: =TeamsTheme.Default
                    TabIndex: =-1
                    Text: =ThisItem.label
                    VerticalAlignment: =VerticalAlign.Top
                    Width: =Parent.TemplateWidth - 24
                    X: =12
                    Y: =13
                    ZIndex: =2

                Rectangle3_4 As rectangle:
                    BorderColor: =RGBA(243, 242, 241, 1)
                    BorderStyle: =BorderStyle.None
                    BorderThickness: =2
                    DisabledFill: =RGBA(238, 140, 29, 1)
                    DisplayMode: =DisplayMode.Disabled
                    Fill: =RGBA(238, 140, 29, 1)
                    FocusedBorderColor: =RGBA(98, 100, 167, 1)
                    Height: =50
                    HoverFill: =RGBA(98, 100, 167, 1)
                    OnSelect: =
                    PressedFill: =RGBA(98, 100, 167, 1)
                    Visible: =If(SettingToDisplay = ThisItem.label, true,false)
                    Width: =12
                    X: =238
                    ZIndex: =3

        RightSideContainer2 As groupContainer.verticalAutoLayoutContainer:
            FillPortions: =7
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingLeft: =15
            PaddingRight: =15
            ZIndex: =3

            HeaderContainer2 As groupContainer.horizontalAutoLayoutContainer:
                FillPortions: =0
                Height: =75
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                ZIndex: =4

                Label13 As Label:
                    AlignInContainer: =AlignInContainer.Stretch
                    Alignment: =Align.Center
                    DisplayMode: =DisplayMode.Edit
                    FillPortions: =1
                    FontSize: =20
                    Height: =32
                    LayoutMinHeight: =32
                    LayoutMinWidth: =320
                    Text: =SettingToDisplay
                    Width: =320
                    X: =0
                    Y: =0
                    ZIndex: =1

            Cnt_Settings_Preferences As groupContainer.verticalAutoLayoutContainer:
                Fill: =RGBA(255, 255, 255, 1)
                LayoutDirection: =LayoutDirection.Vertical
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                PaddingBottom: =10
                PaddingLeft: =10
                PaddingRight: =10
                PaddingTop: =10
                ZIndex: =5

                Label14 As Label:
                    DisplayMode: =DisplayMode.Edit
                    Height: =32
                    LayoutMinHeight: =32
                    LayoutMinWidth: =320
                    PCFTeamsTheme: =TeamsTheme.Default
                    Text: ="'To Do' list to copy outcomes to"
                    Width: =320
                    X: =280
                    Y: =180
                    ZIndex: =1

                "ComboBox4 As 'Combo box'.pcfdataset":
                    DisplayMode: =DisplayMode.Edit
                    Height: =32
                    Items: ='MicrosoftTo-Do(Business)'.GetAllTodoListsV2()
                    LayoutMinHeight: =32
                    LayoutMinWidth: =320
                    PCFTeamsTheme: =TeamsTheme.Default
                    Width: =320
                    X: =0
                    Y: =0
                    ZIndex: =2

                    displayName1 As pcfDataField.textualColumn:
                        FieldDisplayName: ="displayName"
                        FieldName: ="displayName"
                        FieldVariantName: ="textualColumn"
                        Order: =1
                        ZIndex: =6

